# CI / CD Configuration

stages:
  - test
  - deploy

test:aspnet:
  stage: test
  script:
    - dotnet test

test:angular:
  stage: test
  script:
    - yarn --cwd src/siwar install --frozen-lockfile
    - yarn --cwd src/siwar lint
    - yarn --cwd src/siwar test

.deploy: &deploy
  stage: deploy
  script:
    - yarn --cwd src/siwar install --frozen-lockfile
    - yarn --cwd src/siwar run kendo-ui-license activate
    - yarn --cwd src/siwar run build -c $CI_ENVIRONMENT_NAME --base-href /
    - dotnet-gitversion /updateassemblyinfo
    - dotnet publish src/siwar -c Release -o $CI_PROJECT_DIR/Artifacts
    - msdeploy -verb:sync -source:contentPath=$CI_PROJECT_DIR/Artifacts -dest:contentPath=$PUBLISH_APP,ComputerName=$PUBLISH_URL/msdeploy.axd,UserName=`$$PUBLISH_USER,Password=$PUBLISH_PASSWORD,AuthType=Basic -enableRule:AppOffline
  artifacts:
    name: '$CI_JOB_ID'
    paths:
      - '$CI_PROJECT_DIR/Artifacts/'

deploy:staging:
  <<: *deploy
  environment:
    name: staging
    url: https://pulves-staging.azurewebsites.net
  only:
    - main

deploy:production:
  <<: *deploy
  environment:
    name: production
    url: https://pulves.azurewebsites.net
  when: manual
  only:
    - tags
